updated resources download

diff --git a/wgutil b/wgutil
--- a/wgutil
+++ b/wgutil
@@ -3,11 +3,12 @@
 # MAINIF is the name of server's main interface which is connected to the internet.
 # DIR is related to clients. (client's folder)
 # INTERFACE is the name of wireguard interface.
-
-git clone https://github.com/fkia87/resources.git || \
-{ echo -e "Error downloading required files from Github.
+if ! -d ./resources; then
+    git clone https://github.com/fkia87/resources.git || \
+    { echo -e "Error downloading required files from Github.
 Check if \"Git\" is installed and your internet connection is OK." >&2; \
-exit 1; }
+    exit 1; }
+fi
 
 source resources/pkg_management
 source resources/os
