removed resources dependency

diff --git a/wgutil b/wgutil
--- a/wgutil
+++ b/wgutil
@@ -16,8 +16,77 @@ DEFAULTIF="wg0"
 DEFAULTDNS="8.8.8.8"
 ALLOWED_IPS="0.0.0.0/0"
 
+YELLOW='\033[0;33m'
+DECOLOR='\033[0m'
+GREEN='\033[0;32m'
+RED='\033[0;31m'
+
 DEL='No'
 declare -i PORT
+
+err() {
+    echo -e "$1" >&2
+    exit "${2:-1}"
+}
+
+find_mainif() {
+# Sets variable "MAINIF" to the name of the network interface through which 
+# system connects to internet.
+iflist=( $(find /sys/class/net/ | rev | cut -d / -f1 | rev | sed '/^$/d') )
+tmp=( $(\ip route |grep default |sed -e 's/^\s*//;s/\s/\n/g;') )
+
+for var in "${tmp[@]}"; do
+    [[ " ${iflist[*]} " =~ ${var} ]] && MAINIF=$var
+done
+if [[ -z $MAINIF ]]; then
+    echo -e "\nCouldn't determine the main interface on the system.\n" >&2
+    return 1
+fi
+}
+
+checkuser() {
+    [[ $UID == "0" ]] || err "You are not root." "1"
+}
+
+os() {
+    grep -e '^ID=' /etc/os-release \
+        | cut -d = -f 2 | sed -e 's/[[:punct:]]//g' \
+        | tr "[:upper:]" "[:lower:]"
+}
+
+install_pkg() {
+    echo -e "\nInstalling $*..."
+    case $(os) in
+        centos | fedora | almalinux | rocky)
+            yum -y install $@ 2>/dev/null || dnf -y install $@ || return 3
+            sleep 1
+            ;;
+        ubuntu | debian)
+            apt update
+            apt -y install "$@" || return 3
+            sleep 1
+            ;;
+        manjaro | endeavouros | arch*)
+            pacman -Sy --noconfirm $@ || return 3
+            sleep 1
+            ;;
+    esac
+}
+
+getifip() {
+# Returns IP of a given interface.
+# Usage: getifip <interface>
+\ip -4 a show dev "$1" | grep 'inet ' | head -n 1 | awk '{print $2}' | cut -d / -f 1
+}
+
+enable_ipforward() {
+# Checks and enables ip forwarding kernel parameter.
+echo "Checking net.ipv4.ip_forward..."
+if grep '0' /proc/sys/net/ipv4/ip_forward >/dev/null; then
+    echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
+    sysctl -p > /dev/null 2>&1 || return 1
+fi
+}
 
 read_parameters() {
     case $1 in
